### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by larseggert** [cemeyer/structhole#3]
gcc-6 compiled sources with debug info:
```
./structhole w_iov test
struct w_iov {
ZZZ!
structhole.c:237: structprobe: buf: (null)(0)
```
For some structs, no output at all:
```
./structhole w_engine test
```

**Comment by cemeyer** [comment]
Yep.  For the former, some debuginfo isn't being handled, and it must be more common than when I started this tool.

For the latter, it seems like your debuginfo does not include that struct at all.

**Comment by cemeyer** [comment]
If you like, please try the patch I just pushed.  It seems GCC emits `DW_FORM_data*` now.

**Comment by larseggert** [comment]
Seems to work better, thanks!

I get one odd-looking message:
```
!!! XXX ignored pointer qualifier TAG 0x16
```

As to why the debuginfo for w_engine is missing, no idea, but you are right. Compiling with `-O0 -g3` FWIW.

**Comment by cemeyer** [comment]
Yeah, there is definitely a lot of DWARF this little program does not understand yet.  Pointer qualifiers (`const` or whatever) are a gap.  I didn't *need* those to work to use the tool as-is to look for structure holes, so they weren't a priority.
